action_id: trunk-cache-prune
date: 2025-11-01 02:09:11
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1761962951
full_timestamp:
  nanos: 185994000
  seconds: 1761962951
trunk_version: 1.25.0
