@echo off
REM Generated by trunk tool 'black'
set PYTHONUTF8=1
set PATH=C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\black\25.9.0-8841c46f9577314a4a4e2006407de2c0/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\black\25.9.0-8841c46f9577314a4a4e2006407de2c0/Scripts;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set VIRTUAL_ENV=C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\black\25.9.0-8841c46f9577314a4a4e2006407de2c0

start /w /b black %*
