@echo off
REM Generated by trunk tool 'isort'
set PATH=C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\isort\7.0.0-6677305afce7ac706351a44b8b1fb93b/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\isort\7.0.0-6677305afce7ac706351a44b8b1fb93b/Scripts;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\isort\7.0.0-6677305afce7ac706351a44b8b1fb93b

start /w /b isort %*
