@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\osv-scanner\2.2.4-e8f3b117a1f0ad6847275b674408e6b2;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
