@echo off
REM Generated by trunk tool 'ruff'
set PYTHONUTF8=1
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\ruff\0.14.3-b56d663c7d18b60c4d52769bbf9569d5/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\ruff\0.14.3-b56d663c7d18b60c4d52769bbf9569d5/Scripts;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\ruff\0.14.3-b56d663c7d18b60c4d52769bbf9569d5

start /w /b ruff %*
