@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\trufflehog\3.90.12-873886b30c6ffc914074b6f41d0d56d2;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\ROEURN.ROS\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
