action_id: trunk-share-with-everyone
date: 2025-11-01 02:14:16
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1761963256
full_timestamp:
  nanos: 947036000
  seconds: 1761963256
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
